/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../models15/19.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/19.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group scale={54.411}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group rotation={[Math.PI, 0, 0]} scale={110.41}>
                <mesh geometry={nodes.Bench_BenchConcreteBase_0.geometry} material={materials.BenchConcreteBase} />
                <mesh geometry={nodes.Bench_BenchWood_0.geometry} material={materials.BenchWood} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={[50, 22.5, 50]}>
                <mesh geometry={nodes.CeillingWire_CeillingWire_0.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0001.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0002.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0003.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0004.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0005.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.CeillingWire_CeillingWire_0006.geometry} material={materials.CeillingWire} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Lamp_Emissive_0.geometry} material={materials.Emissive} />
                <mesh geometry={nodes.Lamp_Lamp_0.geometry} material={materials.Lamp} />
              </group>
              <group rotation={[-Math.PI / 2, 0, 0]} scale={[50, 22.5, 50]}>
                <mesh geometry={nodes.LampBase_CeillingWire_0.geometry} material={materials.CeillingWire} />
                <mesh geometry={nodes.LampBase_Emissive_0.geometry} material={materials.Emissive} />
              </group>
              <mesh geometry={nodes.PaitingsInside_001_Painting_0.geometry} material={materials.Painting} rotation={[-Math.PI / 2, 0.099, 0]} scale={100} />
              <mesh geometry={nodes.PaitingsOutside_Painting_0.geometry} material={materials.Painting} rotation={[-Math.PI / 2, 0.099, 0]} scale={100} />
              <group rotation={[-Math.PI / 2, 0, 0]} scale={[50, 22.5, 50]}>
                <mesh geometry={nodes.Walls_Ceilling_0.geometry} material={materials.Ceilling} />
                <mesh geometry={nodes.Walls_Emissive_0.geometry} material={materials.Emissive} />
                <mesh geometry={nodes.Walls_Floor_0.geometry} material={materials.Floor} />
                <mesh geometry={nodes.Walls_Walls_0.geometry} material={materials.Walls} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[28.946, 7.559, 33.456]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes['1_FB_Base_low_Legs_0'].geometry} material={materials.Legs} position={[124.803, -468.712, 26.259]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['1_H_Base2_low_Hands_0'].geometry} material={materials.Hands} position={[243.937, -48.225, 77.675]} rotation={[0, 0, 0.037]} scale={100} />
          <mesh geometry={nodes['1_H_Base_low_Hands_0'].geometry} material={materials.Hands} position={[182.029, -40.79, 131.748]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['1_LL_Base_low_Legs_0'].geometry} material={materials.Legs} position={[124.803, -311.246, -108.652]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['1_TL_Base_low_Legs_0'].geometry} material={materials.Legs} position={[124.803, -190.185, 68.06]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.BezierCurve001_low_Hands_0.geometry} material={materials.Hands} position={[237.576, 8.395, 208.868]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.BezierCurve_low_Hands_0.geometry} material={materials.Hands} position={[237.576, 8.395, 214.973]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_low_Hands_0.geometry} material={materials.Hands} position={[262.524, -29.696, 29.47]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube002_low_Hands_0.geometry} material={materials.Hands} position={[279.961, -62.364, 29.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube003_low_Hands_0.geometry} material={materials.Hands} position={[235.512, -144.304, 70.757]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube004_low_Hands_0.geometry} material={materials.Hands} position={[312.836, -132.634, 30.03]} rotation={[-Math.PI / 2, 1.094, 0]} scale={100} />
          <mesh geometry={nodes.Cube005_low_Hands_0.geometry} material={materials.Hands} position={[208.666, -42.617, -95.703]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube006_low_Hands_0.geometry} material={materials.Hands} position={[224.462, -39.871, 28.363]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube007_low_Hands_0.geometry} material={materials.Hands} position={[181.585, -16.444, 65.374]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube009_low_Hands_0.geometry} material={materials.Hands} position={[157.762, 66.888, 12.143]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube010_low_Hands_0.geometry} material={materials.Hands} position={[182.029, -67.594, 131.126]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube011_low_Torse_0.geometry} material={materials.Torse} position={[0, 48.499, -0.542]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube012_low_Hands_0.geometry} material={materials.Hands} position={[157.762, 66.888, 12.143]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube013_low_Torse_0.geometry} material={materials.Torse} position={[78.973, 0.872, -88.299]} rotation={[-1.733, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube014_low_Torse_0.geometry} material={materials.Torse} position={[0, -143.346, -26.643]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube015_low_Torse_0.geometry} material={materials.Torse} position={[22.425, -147.474, 126.97]} rotation={[-1.338, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube016_low_Torse_0.geometry} material={materials.Torse} position={[-26.228, -133.793, 131.692]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube017_low_Legs_0.geometry} material={materials.Legs} position={[174.838, -258.095, 55.656]} rotation={[-1.334, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube018_low_Torse_0.geometry} material={materials.Torse} position={[16.77, 74.927, -106.023]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube019_low_Torse_0.geometry} material={materials.Torse} position={[0, 8.722, 116.362]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube020_low_Torse_0.geometry} material={materials.Torse} position={[0, 39.661, -139.384]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube021_low_Torse_0.geometry} material={materials.Torse} position={[82.754, -25.671, 109.117]} rotation={[-1.157, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube022_low_Torse_0.geometry} material={materials.Torse} position={[97.986, 78.723, -54.244]} rotation={[-0.958, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube023_low_Torse_0.geometry} material={materials.Torse} position={[186.92, 78.723, -54.244]} rotation={[-0.958, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube024_low_Torse_0.geometry} material={materials.Torse} position={[88.934, 142.13, -99.845]} rotation={[-0.955, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube025_low_Torse_0.geometry} material={materials.Torse} position={[33.036, -27.013, -62.544]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube026_low_Torse_0.geometry} material={materials.Torse} position={[-21.676, -202.994, -25.097]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube027_low_Torse_0.geometry} material={materials.Torse} position={[0, 8.722, 116.362]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube028_low_Torse_0.geometry} material={materials.Torse} position={[37.37, 61.519, 115.089]} rotation={[-1.146, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube029_low_Torse_0.geometry} material={materials.Torse} position={[42.168, 54.051, 97.852]} rotation={[-0.994, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube030_low_Torse_0.geometry} material={materials.Torse} position={[42.168, 38.149, 122.272]} rotation={[-0.994, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube031_low_Torse_0.geometry} material={materials.Torse} position={[0, 77.975, 92.567]} rotation={[-1.353, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube032_low_Torse_0.geometry} material={materials.Torse} position={[42.51, -27.054, 161.659]} rotation={[-1.232, 0, 0.722]} scale={100} />
          <mesh geometry={nodes.Cube033_low_Torse_0.geometry} material={materials.Torse} position={[79.48, 19.357, -143.218]} rotation={[-1.934, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube034_low_Torse_0.geometry} material={materials.Torse} position={[78.591, 28.954, -109.043]} rotation={[-1.879, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube035_low_Torse_0.geometry} material={materials.Torse} position={[0, 48.499, -0.542]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube036_low_Torse_0.geometry} material={materials.Torse} position={[0, 48.499, -0.542]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube037_low_Torse_0.geometry} material={materials.Torse} position={[0, 8.722, 115.922]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube038_low_Torse_0.geometry} material={materials.Torse} position={[0, 8.722, 116.362]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube039_low_Torse_0.geometry} material={materials.Torse} position={[0, 8.722, 116.362]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube041_low_Torse_0.geometry} material={materials.Torse} position={[0, -161.538, -67.794]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube042_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -265.424, 100.757]} rotation={[-1.333, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube043_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -250.296, 69.545]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube044_low_Torse_0.geometry} material={materials.Torse} position={[30.414, -85.774, 33.636]} rotation={[-0.756, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube045_low_Legs_0.geometry} material={materials.Legs} position={[181.14, -143.091, -35.048]} rotation={[-1.254, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube046_low_Torse_0.geometry} material={materials.Torse} position={[23.033, -89.004, -110.669]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube047_low_Torse_0.geometry} material={materials.Torse} position={[5.901, -108.475, -86.835]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube048_low_Torse_0.geometry} material={materials.Torse} position={[26.625, -99.495, -57.329]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube049_low_Legs_0.geometry} material={materials.Legs} position={[161.551, -123.774, -14.29]} rotation={[-1.284, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube050_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -190.185, 68.06]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube051_low_Legs_0.geometry} material={materials.Legs} position={[124.813, -167.424, -96.506]} rotation={[-2.067, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube052_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -265.424, 100.757]} rotation={[-1.333, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube053_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -295.155, -16.72]} rotation={[-2.13, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube054_low_Legs_0.geometry} material={materials.Legs} position={[140.463, -461.527, 68.449]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube055_low_Legs_0.geometry} material={materials.Legs} position={[178.357, -460.404, 41.63]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube056_low_Legs_0.geometry} material={materials.Legs} position={[127.848, -354.018, 0.573]} rotation={[-1.019, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube057_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -454.016, 104.264]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube058_low_Legs_0.geometry} material={materials.Legs} position={[140.637, -309.814, -33.803]} rotation={[-0.93, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube060_low_Legs_0.geometry} material={materials.Legs} position={[156.579, -318.049, -74.651]} rotation={[-0.994, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube061_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -305.469, -111.638]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube062_low_Legs_0.geometry} material={materials.Legs} position={[155.32, -446.544, -16.043]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube064_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -451.71, 96.968]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube065_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -473.158, 125.623]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube066_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -448.557, 78.053]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube067_low_Legs_0.geometry} material={materials.Legs} position={[160.787, -466.884, 90.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube068_low_Legs_0.geometry} material={materials.Legs} position={[190.655, -460.801, 30.65]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube069_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -381.993, -44.287]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube071_low_Legs_0.geometry} material={materials.Legs} position={[141.263, -461.75, -47.818]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube072_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -473.046, -45.308]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -48.225, 30.159]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder001_low_Hands_0.geometry} material={materials.Hands} position={[253.238, -42.356, 277.326]} rotation={[0, 0, Math.PI / 3]} scale={100} />
          <mesh geometry={nodes.Cylinder002_low_Hands_0.geometry} material={materials.Hands} position={[243.505, -37.236, 277.326]} rotation={[0, 0, 2.094]} scale={100} />
          <mesh geometry={nodes.Cylinder003_low_Hands_0.geometry} material={materials.Hands} position={[234.205, -43.105, 277.326]} rotation={[0, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Cylinder004_low_Hands_0.geometry} material={materials.Hands} position={[234.637, -54.093, 277.326]} rotation={[0, 0, -2.094]} scale={100} />
          <mesh geometry={nodes.Cylinder005_low_Hands_0.geometry} material={materials.Hands} position={[244.37, -59.214, 277.326]} rotation={[0, 0, -Math.PI / 3]} scale={100} />
          <mesh geometry={nodes.Cylinder006_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -48.225, 276.154]} scale={100} />
          <mesh geometry={nodes.Cylinder007_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -48.225, 258.488]} scale={100} />
          <mesh geometry={nodes.Cylinder008_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -48.225, 108.45]} scale={100} />
          <mesh geometry={nodes.Cylinder009_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -48.225, 287.101]} rotation={[0, 0, 0.039]} scale={100} />
          <mesh geometry={nodes.Cylinder011_low_Hands_0.geometry} material={materials.Hands} position={[265.024, -48.225, -15.992]} scale={100} />
          <mesh geometry={nodes.Cylinder012_low_Hands_0.geometry} material={materials.Hands} position={[243.937, -121.224, 30.371]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder013_low_Hands_0.geometry} material={materials.Hands} position={[133.737, 76.329, 99.401]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder014_low_Hands_0.geometry} material={materials.Hands} position={[182.029, -38.791, 214.973]} scale={100} />
          <mesh geometry={nodes.Cylinder015_low_Hands_0.geometry} material={materials.Hands} position={[168.79, 45.283, 84.027]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder016_low_Hands_0.geometry} material={materials.Hands} position={[176.734, 117.202, -124.699]} rotation={[-2.924, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder017_low_Hands_0.geometry} material={materials.Hands} position={[156.318, 33.443, 12.308]} scale={100} />
          <mesh geometry={nodes.Cylinder018_low_Hands_0.geometry} material={materials.Hands} position={[157.762, 87.704, -28.967]} rotation={[1.823, 0, 0.001]} scale={100} />
          <mesh geometry={nodes.Cylinder019_low_Torse_0.geometry} material={materials.Torse} position={[144.142, 14.943, -16.184]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder020_low_Torse_0.geometry} material={materials.Torse} position={[119.162, -19.914, 83.933]} rotation={[0.5, 1.245, -2.336]} scale={100} />
          <mesh geometry={nodes.Cylinder021_low_Torse_0.geometry} material={materials.Torse} position={[43.07, -71.85, 134.214]} rotation={[-2.766, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder022_low_Torse_0.geometry} material={materials.Torse} position={[27.75, -133.828, 120.825]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder023_low_Torse_0.geometry} material={materials.Torse} position={[24.929, -128.779, 132.298]} scale={100} />
          <mesh geometry={nodes.Cylinder024_low_Torse_0.geometry} material={materials.Torse} position={[34.306, -139.212, 134.679]} scale={100} />
          <mesh geometry={nodes.Cylinder025_low_Torse_0.geometry} material={materials.Torse} position={[0, -118.314, 120.575]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder026_low_Torse_0.geometry} material={materials.Torse} position={[56.65, -93.509, 111.097]} rotation={[-Math.PI / 2, -0.774, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder027_low_Torse_0.geometry} material={materials.Torse} position={[57.572, -93.952, 92.389]} rotation={[-Math.PI / 2, -0.774, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder028_low_Torse_0.geometry} material={materials.Torse} position={[58.774, -94.612, 73.737]} rotation={[-Math.PI / 2, -0.774, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder029_low_Torse_0.geometry} material={materials.Torse} position={[43.07, -71.85, 134.214]} rotation={[-2.766, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder030_low_Torse_0.geometry} material={materials.Torse} position={[0, -87.931, 180.64]} rotation={[-0.792, -1.571, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder031_low_Torse_0.geometry} material={materials.Torse} position={[45.087, 27.321, 152.534]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder032_low_Torse_0.geometry} material={materials.Torse} position={[29.561, 69.424, 106.695]} rotation={[-1.15, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder033_low_Torse_0.geometry} material={materials.Torse} position={[43.07, -71.85, 134.214]} rotation={[-2.766, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder034_low_Torse_0.geometry} material={materials.Torse} position={[33.466, -195.912, -35.32]} scale={100} />
          <mesh geometry={nodes.Cylinder035_low_Torse_0.geometry} material={materials.Torse} position={[50.208, -211.55, -34.09]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder036_low_Torse_0.geometry} material={materials.Torse} position={[27.225, -216.357, -14.01]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder037_low_Torse_0.geometry} material={materials.Torse} position={[27.225, -216.357, -39.938]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder038_low_Torse_0.geometry} material={materials.Torse} position={[50.64, -143.924, -51.729]} rotation={[-1.643, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder039_low_Torse_0.geometry} material={materials.Torse} position={[-76.485, -143.643, -51.561]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder040_low_Torse_0.geometry} material={materials.Torse} position={[56.045, -100.734, -84.387]} scale={100} />
          <mesh geometry={nodes.Cylinder041_low_Torse_0.geometry} material={materials.Torse} position={[0, -73.224, -62.008]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder042_low_Torse_0.geometry} material={materials.Torse} position={[33.196, -31.484, -36.776]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder043_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -249.55, 36.42]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder044_low_Legs_0.geometry} material={materials.Legs} position={[70.114, -269.78, 41.07]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder045_low_Torse_0.geometry} material={materials.Torse} position={[0, -46.861, -75.435]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder046_low_Torse_0.geometry} material={materials.Torse} position={[0, -46.861, -75.435]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder048_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -301.174, 41.834]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder049_low_Legs_0.geometry} material={materials.Legs} position={[176.757, -125.777, -46.574]} rotation={[-2.817, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder050_low_Legs_0.geometry} material={materials.Legs} position={[176.757, -125.777, -46.574]} rotation={[-2.817, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder051_low_Legs_0.geometry} material={materials.Legs} position={[132.362, -201.481, 9.324]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder052_low_Legs_0.geometry} material={materials.Legs} position={[124.235, -320.803, -45.901]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder053_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -332.506, -36.667]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder054_low_Legs_0.geometry} material={materials.Legs} position={[124.229, -363.384, 60.974]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder055_low_Legs_0.geometry} material={materials.Legs} position={[133.471, -418.413, 26.27]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder056_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -372.76, -36.821]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder057_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -466.672, 26.259]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder058_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -432.148, -1.609]} scale={100} />
          <mesh geometry={nodes.Cylinder059_low_Legs_0.geometry} material={materials.Legs} position={[141.016, -468.643, 141.031]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder060_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -432.148, 26.259]} scale={100} />
          <mesh geometry={nodes.Cylinder061_low_Legs_0.geometry} material={materials.Legs} position={[170.908, -448.719, 12.011]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder062_low_Legs_0.geometry} material={materials.Legs} position={[165.418, -471.597, 75.964]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder063_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -468.565, 113.234]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder064_low_Hands_0.geometry} material={materials.Hands} position={[157.762, 87.704, -28.967]} rotation={[1.823, 0, 0.001]} scale={100} />
          <mesh geometry={nodes.Cylinder065_low_Hands_0.geometry} material={materials.Hands} position={[157.762, 87.704, -28.967]} rotation={[1.823, 0, 0.001]} scale={100} />
          <mesh geometry={nodes.Cylinder066_low_Legs_0.geometry} material={materials.Legs} position={[176.983, -460.693, 66.062]} scale={100} />
          <mesh geometry={nodes.Cylinder067_low_Legs_0.geometry} material={materials.Legs} position={[153.415, -467.131, -21.769]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder_low_Hands_0.geometry} material={materials.Hands} position={[253.67, -53.345, 277.326]} scale={100} />
          <mesh geometry={nodes.Floor001_Floor_0.geometry} material={materials['Floor.001']} position={[-220.636, -482.84, 234.48]} rotation={[-Math.PI / 2, 0, 0]} scale={229.575} />
          <mesh geometry={nodes.NurbsPath001_low_Torse_0.geometry} material={materials.Torse} position={[0, -34.286, 0]} rotation={[-Math.PI / 2, 0, 1.557]} scale={100} />
          <mesh geometry={nodes.NurbsPath002_low_Torse_0.geometry} material={materials.Torse} position={[6.418, 0, -1.689]} rotation={[-Math.PI / 2, 0, 1.385]} scale={100} />
          <mesh geometry={nodes.NurbsPath003_low_Torse_0.geometry} material={materials.Torse} position={[0.376, -50.425, -95.491]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.NurbsPath005_low_Legs_0.geometry} material={materials.Legs} position={[133.471, -408.32, 36.521]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.NurbsPath006_low_Legs_0.geometry} material={materials.Legs} position={[133.471, -408.32, 36.521]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Plane001_low_Torse_0.geometry} material={materials.Torse} position={[81.417, -84.595, -45.035]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane002_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -290.401, -110.373]} rotation={[-2.191, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane003_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -318.297, -120.67]} rotation={[2.858, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane004_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -351.313, 44.701]} rotation={[-1.035, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane005_low_Legs_0.geometry} material={materials.Legs} position={[124.803, -426.264, 104.518]} rotation={[-0.259, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane_low_Torse_0.geometry} material={materials.Torse} position={[88.934, 110.465, -57.753]} rotation={[-0.964, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sphere_low_Torse_0.geometry} material={materials.Torse} position={[0, 12.034, -141.475]} rotation={[-1.096, 0, 0]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes['tripo_node_d5d7a45d-0f3d-443e-a721-a52008c88198'].geometry} material={materials['tripo_mat_d5d7a45d-0f3d-443e-a721-a52008c88198']} position={[-243.812, 123.317, 22.795]} rotation={[-0.005, -0.036, 0]} scale={[169.511, 285.253, 259.532]} />
    </group>
  )
}

useGLTF.preload('/19.glb')
